title: <p align="center"> Muthu Jeyanthi Prakash </p>
description:
  <p align="center">
  <a href="profile/Mehdyhkn_Cv.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muthu-jeyanthi/">LinkedIn</a> |
  <a href="https://github.com/Mehdyhkn">GitHub</a>
  </p>
  
  <p align="justify">
  I am a data scientist with a master's degree in statistical and stochastic modeling
   and a master's degree in fundamental mathematics.
  <br><br>
  I love to learn by doing projects which I've compiled under the most in portfolio section 
  along with internship and AI challenge projects. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
